### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by jimmysjolund** [susestudio/kanban#2]
This looks very good and is just what I'm looking for for my day to day work. However, just doing a git clone and try to run fails. As for others who like me are not Ruby developers I see a need for a more extensive instruction on how to get it to run on your machine.

Without any preconfigurations or installations I get:
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- haml (LoadError)

I'm running Fedora 27 and have tried several instructions online on how to install Ruby but none so far has made it possible to run:

`./bin/kanban data.txt`

I understand this might be a dropped project but I'm giving this issue a try.

**Comment by cornelius** [comment]
Hi Jimmy,

thanks for finding this project. I forgot about it ;-) I added some basic installation instructions now. Maybe that helps.

Best Regards,
Cornelius
